### ISSUE TITLE
ichimillのライセンス失効

### ISSUE THREAD

**Issue by nkm071** [hellocit/GNSS-research#7]
ichimillを無料で使用できる期間が過ぎた．またTFをrosbagで取得する際にgnss_linkを起動していなかったため，現状のrosbagでは計算を行えない．

**Comment by nkm071** [comment]
従ってichimillの再契約を行う必要がある．

**Comment by nkm071** [comment]
% roslaunch f9p_ichimill gps_ichimill.launch                                                                                                                                                           [~]
... logging to /home/neko/.ros/log/96bdce2e-c172-11ec-82c4-00044be58c4c/roslaunch-neko-R5-TA5-20845.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/neko/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

started roslaunch server http://192.168.122.1:42971/

SUMMARY
========

PARAMETERS
 * /f9p_driver/baud: 230400
 * /f9p_driver/debug: True
 * /f9p_driver/port: /dev/rfcomm0
 * /ichimill_connect/debug: True
 * /ichimill_connect/host: ntrip.ales-corp.c...
 * /ichimill_connect/mountpoint: RTCM32M7S
 * /ichimill_connect/password: lv7fza
 * /ichimill_connect/port: 2101
 * /ichimill_connect/username: tjo6s56s
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    f9p_driver (f9p_ichimill/f9p_driver.py)
    ichimill_connect (f9p_ichimill/ichimill_connect.py)
    nmea_topic_driver (nmea_navsat_driver/nmea_topic_driver)

ROS_MASTER_URI=http://192.168.0.172:11311

process[f9p_driver-1]: started with pid [20868]
process[ichimill_connect-2]: started with pid [20869]
process[nmea_topic_driver-3]: started with pid [20903]
[INFO] [1704683805.723569]: NTRIP Caster connecting...
[INFO] [1704683805.799353]: ok
[INFO] [1704683805.802349]: Header sending...
HTTP/1.1 401 Unauthorized
Server: NTRIP Caster
WWW-Authenticate: Basic realm="/RTCM32M7S"


[ERROR] [1704683805.846803]: Caster ResponseError!! : HTTP/1.1 401 Unauthorized
Server: NTRIP Caster
WWW-Authenticate: Basic realm="/RTCM32M7S"


[INFO] [1704683805.850523]: NTRIP Caster disconnect
[ichimill_connect-2] process has finished cleanly
log file: /home/neko/.ros/log/96bdce2e-c172-11ec-82c4-00044be58c4c/ichimill_connect-2*.log
[ERROR] [1704684293.091681]: SerialException error(None): None
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/registration.py", line 375, in cleanup
    multi()
  File "/usr/lib/python3.8/xmlrpc/client.py", line 879, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 669, in _ServerProxy__request
    return xmlrpcclient.ServerProxy._ServerProxy__request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1153, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1165, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1278, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.8/xmlrpc/client.py", line 1308, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/core.py", line 579, in signal_shutdown
    h(reason)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/registration.py", line 377, in cleanup
    (se_errno, msg) = se.args
ValueError: not enough values to unpack (expected 2, got 1)
[f9p_driver-1] process has finished cleanly
log file: /home/neko/.ros/log/96bdce2e-c172-11ec-82c4-00044be58c4c/f9p_driver-1*.log

**Comment by nkm071** [comment]
上記のようなエラーがでたため，再契約が必要と結論付ける

**Comment by nkm071** [comment]
契約するためのフォームを送付したためissueを閉じる
